
package snake;

import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class Snake extends javax.swing.JFrame {

    
    public Snake() {
        initComponents();
        
       
        
       
             btnReset.setVisible(false);
     lblValue.setVisible(false);
     lblTurn.setVisible(false);
     btnOne.setVisible(false);
     btnTwo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        lbl100 = new javax.swing.JLabel();
        lbl99 = new javax.swing.JLabel();
        lbl98 = new javax.swing.JLabel();
        lbl97 = new javax.swing.JLabel();
        lbl96 = new javax.swing.JLabel();
        lbl95 = new javax.swing.JLabel();
        lbl94 = new javax.swing.JLabel();
        lbl93 = new javax.swing.JLabel();
        lbl92 = new javax.swing.JLabel();
        lbl91 = new javax.swing.JLabel();
        lbl90 = new javax.swing.JLabel();
        lbl89 = new javax.swing.JLabel();
        lbl88 = new javax.swing.JLabel();
        lbl87 = new javax.swing.JLabel();
        lbl86 = new javax.swing.JLabel();
        lbl85 = new javax.swing.JLabel();
        lbl84 = new javax.swing.JLabel();
        lbl83 = new javax.swing.JLabel();
        lbl82 = new javax.swing.JLabel();
        lbl81 = new javax.swing.JLabel();
        lbl71 = new javax.swing.JLabel();
        lbl72 = new javax.swing.JLabel();
        lbl73 = new javax.swing.JLabel();
        lbl74 = new javax.swing.JLabel();
        lbl75 = new javax.swing.JLabel();
        lbl76 = new javax.swing.JLabel();
        lbl77 = new javax.swing.JLabel();
        lbl78 = new javax.swing.JLabel();
        lbl79 = new javax.swing.JLabel();
        lbl80 = new javax.swing.JLabel();
        lbl70 = new javax.swing.JLabel();
        lbl69 = new javax.swing.JLabel();
        lbl68 = new javax.swing.JLabel();
        lbl67 = new javax.swing.JLabel();
        lbl66 = new javax.swing.JLabel();
        lbl65 = new javax.swing.JLabel();
        lbl64 = new javax.swing.JLabel();
        lbl63 = new javax.swing.JLabel();
        lbl62 = new javax.swing.JLabel();
        lbl61 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        lbl52 = new javax.swing.JLabel();
        lbl53 = new javax.swing.JLabel();
        lbl54 = new javax.swing.JLabel();
        lbl55 = new javax.swing.JLabel();
        lbl56 = new javax.swing.JLabel();
        lbl57 = new javax.swing.JLabel();
        lbl58 = new javax.swing.JLabel();
        lbl59 = new javax.swing.JLabel();
        lbl60 = new javax.swing.JLabel();
        lbl50 = new javax.swing.JLabel();
        lbl49 = new javax.swing.JLabel();
        lbl48 = new javax.swing.JLabel();
        lbl47 = new javax.swing.JLabel();
        lbl46 = new javax.swing.JLabel();
        lbl45 = new javax.swing.JLabel();
        lbl44 = new javax.swing.JLabel();
        lbl43 = new javax.swing.JLabel();
        lbl42 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl36 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();
        lbl38 = new javax.swing.JLabel();
        lbl39 = new javax.swing.JLabel();
        lbl40 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        lblTurn = new javax.swing.JLabel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        lblValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblSnake1 = new javax.swing.JLabel();
        lblSnake2 = new javax.swing.JLabel();
        lblLadder1 = new javax.swing.JLabel();
        lblLadder2 = new javax.swing.JLabel();
        lblLadder3 = new javax.swing.JLabel();
        lblLadder4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnl.setBackground(new java.awt.Color(7, 63, 86));
        pnl.setLayout(null);

        lbl100.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl100.setText("100");
        lbl100.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl100.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl100);
        lbl100.setBounds(69, 68, 50, 50);

        lbl99.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl99.setText("99");
        lbl99.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl99.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl99);
        lbl99.setBounds(125, 68, 50, 50);

        lbl98.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl98.setText("98");
        lbl98.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl98.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl98);
        lbl98.setBounds(181, 68, 50, 50);

        lbl97.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl97.setText("97");
        lbl97.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl97.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl97);
        lbl97.setBounds(237, 68, 50, 50);

        lbl96.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl96.setText("96");
        lbl96.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl96.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl96);
        lbl96.setBounds(293, 68, 50, 50);

        lbl95.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl95.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl95.setText("95");
        lbl95.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl95.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl95);
        lbl95.setBounds(349, 68, 50, 50);

        lbl94.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl94.setText("94");
        lbl94.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl94.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl94);
        lbl94.setBounds(405, 68, 50, 50);

        lbl93.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl93.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl93.setText("93");
        lbl93.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl93.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl93);
        lbl93.setBounds(461, 68, 50, 50);

        lbl92.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl92.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl92.setText("92");
        lbl92.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl92.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl92);
        lbl92.setBounds(517, 68, 50, 50);

        lbl91.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl91.setText("91");
        lbl91.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl91.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl91);
        lbl91.setBounds(573, 68, 50, 50);

        lbl90.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl90.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl90.setText("90");
        lbl90.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl90.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl90);
        lbl90.setBounds(573, 124, 50, 50);

        lbl89.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl89.setText("89");
        lbl89.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl89.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl89);
        lbl89.setBounds(517, 124, 50, 50);

        lbl88.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl88.setText("88");
        lbl88.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl88.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl88);
        lbl88.setBounds(461, 124, 50, 50);

        lbl87.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl87.setText("87");
        lbl87.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl87.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl87);
        lbl87.setBounds(405, 124, 50, 50);

        lbl86.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl86.setText("86");
        lbl86.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl86.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl86);
        lbl86.setBounds(349, 124, 50, 50);

        lbl85.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl85.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl85.setText("85");
        lbl85.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl85.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl85);
        lbl85.setBounds(293, 124, 50, 50);

        lbl84.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl84.setText("84");
        lbl84.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl84.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl84);
        lbl84.setBounds(237, 124, 50, 50);

        lbl83.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl83.setText("83");
        lbl83.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl83.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl83);
        lbl83.setBounds(181, 124, 50, 50);

        lbl82.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl82.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl82.setText("82");
        lbl82.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl82.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl82);
        lbl82.setBounds(125, 124, 50, 50);

        lbl81.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl81.setText("81");
        lbl81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl81.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl81);
        lbl81.setBounds(69, 124, 50, 50);

        lbl71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl71.setText("71");
        lbl71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl71.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl71);
        lbl71.setBounds(573, 180, 50, 50);

        lbl72.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl72.setText("72");
        lbl72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl72.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl72);
        lbl72.setBounds(517, 180, 50, 50);

        lbl73.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl73.setText("73");
        lbl73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl73.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl73);
        lbl73.setBounds(461, 180, 50, 50);

        lbl74.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl74.setText("74");
        lbl74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl74.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl74);
        lbl74.setBounds(405, 180, 50, 50);

        lbl75.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl75.setText("75");
        lbl75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl75.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl75);
        lbl75.setBounds(349, 180, 50, 50);

        lbl76.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl76.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl76.setText("76");
        lbl76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl76.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl76);
        lbl76.setBounds(293, 180, 50, 50);

        lbl77.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl77.setText("77");
        lbl77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl77.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl77);
        lbl77.setBounds(237, 180, 50, 50);

        lbl78.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl78.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl78.setText("78");
        lbl78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl78.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl78);
        lbl78.setBounds(181, 180, 50, 50);

        lbl79.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl79.setText("79");
        lbl79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl79.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl79);
        lbl79.setBounds(125, 180, 50, 50);

        lbl80.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl80.setText("80");
        lbl80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl80.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl80);
        lbl80.setBounds(69, 180, 50, 50);

        lbl70.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl70.setText("70");
        lbl70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl70.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl70);
        lbl70.setBounds(573, 236, 50, 50);

        lbl69.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl69.setText("69");
        lbl69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl69.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl69);
        lbl69.setBounds(517, 236, 50, 50);

        lbl68.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl68.setText("68");
        lbl68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl68.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl68);
        lbl68.setBounds(461, 236, 50, 50);

        lbl67.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl67.setText("67");
        lbl67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl67.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl67);
        lbl67.setBounds(405, 236, 50, 50);

        lbl66.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl66.setText("66");
        lbl66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl66.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl66);
        lbl66.setBounds(349, 236, 50, 50);

        lbl65.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl65.setText("65");
        lbl65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl65.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl65);
        lbl65.setBounds(293, 236, 50, 50);

        lbl64.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl64.setText("64");
        lbl64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl64.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl64);
        lbl64.setBounds(237, 236, 50, 50);

        lbl63.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl63.setText("63");
        lbl63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl63);
        lbl63.setBounds(181, 236, 50, 50);

        lbl62.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl62.setText("62");
        lbl62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl62);
        lbl62.setBounds(125, 236, 50, 50);

        lbl61.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl61.setText("61");
        lbl61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl61.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl61);
        lbl61.setBounds(69, 236, 50, 50);

        lbl51.setBackground(new java.awt.Color(255, 255, 255));
        lbl51.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl51.setText("51");
        lbl51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl51.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl51);
        lbl51.setBounds(573, 292, 50, 50);

        lbl52.setBackground(new java.awt.Color(255, 255, 255));
        lbl52.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl52.setText("52");
        lbl52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl52.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl52);
        lbl52.setBounds(517, 292, 50, 50);

        lbl53.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl53.setText("53");
        lbl53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl53.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl53);
        lbl53.setBounds(461, 292, 50, 50);

        lbl54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl54.setText("54");
        lbl54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl54);
        lbl54.setBounds(405, 292, 50, 50);

        lbl55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl55.setText("55");
        lbl55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl55);
        lbl55.setBounds(349, 292, 50, 50);

        lbl56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl56.setText("56");
        lbl56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl56);
        lbl56.setBounds(293, 292, 50, 50);

        lbl57.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl57.setText("57");
        lbl57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl57);
        lbl57.setBounds(237, 292, 50, 50);

        lbl58.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl58.setText("58");
        lbl58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl58.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl58);
        lbl58.setBounds(181, 292, 50, 50);

        lbl59.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl59.setText("59");
        lbl59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl59.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl59);
        lbl59.setBounds(125, 292, 50, 50);

        lbl60.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl60.setText("60");
        lbl60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl60.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl60);
        lbl60.setBounds(69, 292, 50, 50);

        lbl50.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl50.setText("50");
        lbl50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl50);
        lbl50.setBounds(573, 348, 50, 50);

        lbl49.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl49.setText("49");
        lbl49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl49);
        lbl49.setBounds(517, 348, 50, 50);

        lbl48.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl48.setText("48");
        lbl48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl48.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl48);
        lbl48.setBounds(461, 348, 50, 50);

        lbl47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl47.setText("47");
        lbl47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl47.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl47);
        lbl47.setBounds(405, 348, 50, 50);

        lbl46.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl46.setText("46");
        lbl46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl46.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl46);
        lbl46.setBounds(349, 348, 50, 50);

        lbl45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl45.setText("45");
        lbl45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl45.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl45);
        lbl45.setBounds(293, 348, 50, 50);

        lbl44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl44.setText("44");
        lbl44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl44);
        lbl44.setBounds(237, 348, 50, 50);

        lbl43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl43.setText("43");
        lbl43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl43.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl43);
        lbl43.setBounds(181, 348, 50, 50);

        lbl42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl42.setText("42");
        lbl42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl42.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl42);
        lbl42.setBounds(125, 348, 50, 50);

        lbl41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl41.setText("41");
        lbl41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl41.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl41);
        lbl41.setBounds(69, 348, 50, 50);

        lbl31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl31.setText("31");
        lbl31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl31);
        lbl31.setBounds(573, 404, 50, 50);

        lbl32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl32.setText("32");
        lbl32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl32);
        lbl32.setBounds(517, 404, 50, 50);

        lbl33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl33.setText("33");
        lbl33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl33);
        lbl33.setBounds(461, 404, 50, 50);

        lbl34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl34.setText("34");
        lbl34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl34);
        lbl34.setBounds(405, 404, 50, 50);

        lbl35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl35.setText("35");
        lbl35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl35);
        lbl35.setBounds(349, 404, 50, 50);

        lbl36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl36.setText("36");
        lbl36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl36);
        lbl36.setBounds(293, 404, 50, 50);

        lbl37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl37.setText("37");
        lbl37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl37);
        lbl37.setBounds(237, 404, 50, 50);

        lbl38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl38.setText("38");
        lbl38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl38);
        lbl38.setBounds(181, 404, 50, 50);

        lbl39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl39.setText("39");
        lbl39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl39);
        lbl39.setBounds(125, 404, 50, 50);

        lbl40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl40.setText("40");
        lbl40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl40.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl40);
        lbl40.setBounds(69, 404, 50, 50);

        lbl30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl30.setText("30");
        lbl30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl30);
        lbl30.setBounds(573, 460, 50, 50);

        lbl29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl29.setText("29");
        lbl29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl29);
        lbl29.setBounds(517, 460, 50, 50);

        lbl28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl28.setText("28");
        lbl28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl28);
        lbl28.setBounds(461, 460, 50, 50);

        lbl27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl27.setText("27");
        lbl27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl27);
        lbl27.setBounds(405, 460, 50, 50);

        lbl26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl26.setText("26");
        lbl26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl26);
        lbl26.setBounds(349, 460, 50, 50);

        lbl25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl25.setText("25");
        lbl25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl25);
        lbl25.setBounds(293, 460, 50, 50);

        lbl24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl24.setText("24");
        lbl24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl24);
        lbl24.setBounds(237, 460, 50, 50);

        lbl23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl23.setText("23");
        lbl23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl23);
        lbl23.setBounds(181, 460, 50, 50);

        lbl22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl22.setText("22");
        lbl22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl22);
        lbl22.setBounds(125, 460, 50, 50);

        lbl21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl21.setText("21");
        lbl21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl21);
        lbl21.setBounds(69, 460, 50, 50);

        lbl11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl11.setText("11");
        lbl11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl11);
        lbl11.setBounds(573, 520, 50, 50);

        lbl12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl12.setText("12");
        lbl12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl12);
        lbl12.setBounds(517, 520, 50, 50);

        lbl13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl13.setText("13");
        lbl13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl13);
        lbl13.setBounds(461, 520, 50, 50);

        lbl14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl14.setText("14");
        lbl14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl14);
        lbl14.setBounds(405, 520, 50, 50);

        lbl15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl15.setText("15");
        lbl15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl15);
        lbl15.setBounds(349, 520, 50, 50);

        lbl16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl16.setText("16");
        lbl16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl16);
        lbl16.setBounds(293, 520, 50, 50);

        lbl17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl17.setText("17");
        lbl17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl17);
        lbl17.setBounds(237, 520, 50, 50);

        lbl18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl18.setText("18");
        lbl18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl18);
        lbl18.setBounds(181, 520, 50, 50);

        lbl19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl19.setText("19");
        lbl19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl19);
        lbl19.setBounds(125, 520, 50, 50);

        lbl20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl20.setText("20");
        lbl20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl20);
        lbl20.setBounds(69, 520, 50, 50);

        lbl10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl10.setText("10");
        lbl10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl10);
        lbl10.setBounds(573, 576, 50, 50);

        lbl9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl9.setText("9");
        lbl9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl9);
        lbl9.setBounds(517, 576, 50, 50);

        lbl8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl8.setText("8");
        lbl8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl8);
        lbl8.setBounds(461, 576, 50, 50);

        lbl7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl7.setText("7");
        lbl7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl7);
        lbl7.setBounds(405, 576, 50, 50);

        lbl6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("6");
        lbl6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl6);
        lbl6.setBounds(349, 576, 50, 50);

        lbl5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("5");
        lbl5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl5);
        lbl5.setBounds(293, 576, 50, 50);

        lbl4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("4");
        lbl4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl4);
        lbl4.setBounds(237, 576, 50, 50);

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("3");
        lbl3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl3);
        lbl3.setBounds(181, 576, 50, 50);

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("2");
        lbl2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl2);
        lbl2.setBounds(125, 576, 50, 50);

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("1");
        lbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl.add(lbl1);
        lbl1.setBounds(69, 576, 50, 50);

        lblP2.setBackground(new java.awt.Color(0, 255, 51));
        lblP2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblP2.setForeground(new java.awt.Color(51, 204, 0));
        lblP2.setText("Player 2: GREEN");
        lblP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl.add(lblP2);
        lblP2.setBounds(673, 135, 147, 34);

        lblP1.setBackground(new java.awt.Color(255, 255, 255));
        lblP1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblP1.setForeground(new java.awt.Color(255, 255, 0));
        lblP1.setText("Player 1: YELLOW");
        lblP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl.add(lblP1);
        lblP1.setBounds(673, 79, 147, 34);

        btnPlay.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlay.setText("Let's Play");
        btnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnl.add(btnPlay);
        btnPlay.setBounds(717, 516, 209, 50);

        lblTurn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTurn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl.add(lblTurn);
        lblTurn.setBounds(673, 240, 170, 36);

        btnOne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnOne.setText("1st");
        btnOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });
        pnl.add(btnOne);
        btnOne.setBounds(673, 404, 83, 50);

        btnTwo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTwo.setText("2nd");
        btnTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });
        pnl.add(btnTwo);
        btnTwo.setBounds(774, 404, 83, 50);

        lblValue.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl.add(lblValue);
        lblValue.setBounds(673, 294, 90, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Game Starts With 6...");
        pnl.add(jLabel1);
        jLabel1.setBounds(680, 600, 200, 40);

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnl.add(btnReset);
        btnReset.setBounds(830, 290, 90, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Both: White");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl.add(jLabel2);
        jLabel2.setBounds(840, 110, 140, 30);

        lblSnake1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Snake1.png"))); // NOI18N
        pnl.add(lblSnake1);
        lblSnake1.setBounds(150, 20, 400, 420);

        lblSnake2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Snake3.png"))); // NOI18N
        pnl.add(lblSnake2);
        lblSnake2.setBounds(180, 250, 370, 310);

        lblLadder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ladderrrr.png"))); // NOI18N
        pnl.add(lblLadder1);
        lblLadder1.setBounds(90, 420, 70, 70);

        lblLadder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ladderrrr.png"))); // NOI18N
        pnl.add(lblLadder2);
        lblLadder2.setBounds(90, 200, 70, 80);

        lblLadder3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ladderrrr.png"))); // NOI18N
        pnl.add(lblLadder3);
        lblLadder3.setBounds(540, 140, 90, 80);

        lblLadder4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ladderrrr.png"))); // NOI18N
        pnl.add(lblLadder4);
        lblLadder4.setBounds(540, 470, 90, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1017, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
    
     lblValue.setVisible(true);
     btnReset.setVisible(true);
     btnOne.setVisible(true);
     btnTwo.setVisible(true);
     btnOne.setEnabled(true);
     btnTwo.setEnabled(false);
     lblTurn.setVisible(true);
     lblTurn.setText("Player 1 Turn :");
     btnPlay.setVisible(false);
        
    }//GEN-LAST:event_btnPlayActionPerformed
    int diceNum1,score1=0,diceNum2,score2=0;
    Random ran = new Random();
    boolean true1=false,true2=false;
    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        // TODO add your handling code here:
        diceNum1 = ran.nextInt(6)+1;
        
        if(!true1){
           btnOne.setEnabled(false);
            btnTwo.setEnabled(true);
            lblValue.setText(""+diceNum1);
            lblTurn.setText("Player 2 Turn:"); 
            if(diceNum1==6)
        {
            true1=true;
        }
        }
        if(true1)
        {
            lblValue.setText(""+diceNum1);
            
     
            // For Previous Position Color
            playersBoard(score1, Color.black);
            score1+=diceNum1;
            
            if(score1>101)
                score1-=diceNum1;
            
            //Ladder
            if(score1==12||score1==21||score1==61||score1==72)
            {
                if(score1==12) score1+=18;
                if(score1==21) score1+=18;
                if(score1==61) score1+=18;
                if(score1==72) score1+=18;
                JOptionPane.showMessageDialog(this, "Ladder: Jump to "+score1+" : ");
            }
            
            //Snake
            if(score1==99||score1==69)
            {
                if(score1==99) score1-=50;
                if(score1==69) score1-=51;
                JOptionPane.showMessageDialog(this, "Snake: Go to "+score1+" : ");
            }
            
            // For New Turn Color
            playersBoard(score1, Color.yellow);
            
            
            // For both on Same number
            if(score1==score2)
                playersBoard(score1, Color.WHITE);
            else
            {
               playersBoard(score1, Color.yellow);
               playersBoard(score2, Color.green);
            }
            
            btnOne.setEnabled(false);
            btnTwo.setEnabled(true);
            lblTurn.setText("Player 2nd Turn:");
        }
        if(score1==101)
        {
            true1 = false;
            true2=false;
            
            JOptionPane.showMessageDialog(this, "Player 1 Win This Match");
            btnPlay.setVisible(true);
            score1=0;
            score2=0;
            lblTurn.setText("Player 1 Turn:");
            lblTurn.setVisible(false);
            
            lblValue.setText("");
            lblValue.setVisible(false);
            for(int i=0;i<100;i++)
            {
                playersBoard(i, Color.black);
            }
            
            btnReset.setVisible(false);
            btnOne.setVisible(false);
            btnTwo.setVisible(false);
        }
        
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        // TODO add your handling code here:
        
        
          diceNum2 = ran.nextInt(6)+1;
        
        if(!true2){
            btnOne.setEnabled(true);
            btnTwo.setEnabled(false);
            lblValue.setText(""+diceNum2);
            lblTurn.setText("Player 1 Turn:");
        if(diceNum2==6)
        {
            true2=true;
        }
        }
        if(true2)
        {
            lblValue.setText(""+diceNum2);
            
            // For Previous Position Color
            playersBoard(score2, Color.black);
            score2+=diceNum2;
        
            if(score2>101)
                score2-=diceNum2;
            
            
            
            
            //Ladder
            if(score2==12||score2==21||score2==61||score2==72)
            {
                if(score2==12) score2+=18;
                if(score2==21) score2+=18;
                if(score2==61) score2+=18;
                if(score2==72) score2+=18;
                JOptionPane.showMessageDialog(this, "Ladder: Jump to "+score2+" : ");
            }
            
            //Snake
            if(score2==99||score2==69)
            {
                if(score2==99) score2-=50;
                if(score2==69) score2-=51;
                JOptionPane.showMessageDialog(this, "Snake: Go to "+score2+" : ");
            }
            
            
            
            // For New Turn Color
            playersBoard(score2, Color.GREEN);
            
            // For both on Same number
            if(score1==score2)
                playersBoard(score1, Color.white);
            else
            {
               playersBoard(score1, Color.yellow);
               playersBoard(score2, Color.green);
            }
            
            btnOne.setEnabled(true);
            btnTwo.setEnabled(false);
            lblTurn.setText("Player 1st Turn:");
        }
        if(score2==101)
        {
            true1 = false;
            true2=false;
            JOptionPane.showMessageDialog(this, "Player 2 Win This Match");
            btnPlay.setVisible(true);
            score1=0;
            score2=0;
            lblTurn.setText("Player 1 Turn:");
            lblTurn.setVisible(false);
            
            lblValue.setText("");
            lblValue.setVisible(false);
            for(int i=1;i<=100;i++)
            {
                playersBoard(i, Color.black);
            }
            
            btnReset.setVisible(false);            
            btnOne.setVisible(false);
            btnTwo.setVisible(false);
        }
        
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        btnPlay.setVisible(true);
            score1=0;
            score2=0;
            true1 = false;
            true2=false;
            
            
            lblTurn.setText("Player 1 Turn:");
            lblTurn.setVisible(false);
            
            lblValue.setText("");
            lblValue.setVisible(false);
            for(int i=1;i<=100;i++)
            {
                playersBoard(i, Color.black);
            }
            btnReset.setVisible(false);
            btnOne.setVisible(false);
            btnTwo.setVisible(false);
    }//GEN-LAST:event_btnResetActionPerformed

    
    public void playersBoard(int x,Color col)
    {
        switch(x){
                case 1:
                lbl1.setForeground(col);
                break;
                case 2:
                lbl2.setForeground(col);
                break;
                case 3:
                lbl3.setForeground(col);
                break;
                case 4:
                lbl4.setForeground(col);
                break;
                case 5:
                lbl5.setForeground(col);
                break;
                case 6:
                lbl6.setForeground(col);
                break;
                case 7:
                lbl7.setForeground(col);
                break;
                case 8:
                lbl8.setForeground(col);
                break;
                case 9:
                lbl9.setForeground(col);
                break;
                case 10:
                lbl10.setForeground(col);
                break;
                case 11:
                lbl11.setForeground(col);
                break;
                case 12:
                lbl12.setForeground(col);
                break;
                case 13:
                lbl13.setForeground(col);
                break;
                case 14:
                lbl14.setForeground(col);
                break;
                case 15:
                lbl15.setForeground(col);
                break;
                case 16:
                lbl16.setForeground(col);
                break;
                case 17:
                lbl17.setForeground(col);
                break;case 18:
                lbl18.setForeground(col);
                break;
                case 19:
                lbl19.setForeground(col);
                break;
                case 20:
                lbl20.setForeground(col);
                break;
                case 21:
                lbl21.setForeground(col);
                break;
                case 22:
                lbl22.setForeground(col);
                break;
                case 23:
                lbl23.setForeground(col);
                break;
                case 24:
                lbl24.setForeground(col);
                break;
                case 25:
                lbl25.setForeground(col);
                break;
                case 26:
                lbl26.setForeground(col);
                break;
                case 27:
                lbl27.setForeground(col);
                break;
                case 28:
                lbl28.setForeground(col);
                break;
                case 29:
                lbl29.setForeground(col);
                break;
                case 30:
                lbl30.setForeground(col);
                break;
                case 31:
                lbl31.setForeground(col);
                break;
                case 32:
                lbl32.setForeground(col);
                break;
                case 33:
                lbl33.setForeground(col);
                break;
                case 34:
                lbl34.setForeground(col);
                break;
                case 35:
                lbl35.setForeground(col);
                break;
                case 36:
                lbl36.setForeground(col);
                break;
                case 37:
                lbl37.setForeground(col);
                break;
                case 38:
                lbl38.setForeground(col);
                break;
                case 39:
                lbl39.setForeground(col);
                break;
                case 40:
                lbl40.setForeground(col);
                break;
                case 41:
                lbl41.setForeground(col);
                break;
                case 42:
                lbl42.setForeground(col);
                break;
                case 43:
                lbl43.setForeground(col);
                break;
                case 44:
                lbl44.setForeground(col);
                break;
                case 45:
                lbl45.setForeground(col);
                break;
                case 46:
                lbl46.setForeground(col);
                break;
                case 47:
                lbl47.setForeground(col);
                break;
                case 48:
                lbl48.setForeground(col);
                break;
                case 49:
                lbl49.setForeground(col);
                break;
                case 50:
                lbl50.setForeground(col);
                break;
                case 51:
                lbl51.setForeground(col);
                break;
                case 52:
                lbl52.setForeground(col);
                break;
                case 53:
                lbl53.setForeground(col);
                break;
                case 54:
                lbl54.setForeground(col);
                break;
                case 55:
                lbl55.setForeground(col);
                break;
                case 56:
                lbl56.setForeground(col);
                break;
                case 57:
                lbl57.setForeground(col);
                break;
                case 58:
                lbl58.setForeground(col);
                break;
                case 59:
                lbl59.setForeground(col);
                break;
                case 60:
                lbl60.setForeground(col);
                break;
                case 61:
                lbl61.setForeground(col);
                break;
                case 62:
                lbl62.setForeground(col);
                break;
                case 63:
                lbl63.setForeground(col);
                break;
                case 64:
                lbl64.setForeground(col);
                break;
                case 65:
                lbl65.setForeground(col);
                break;
                case 66:
                lbl66.setForeground(col);
                break;
                case 67:
                lbl67.setForeground(col);
                break;
                case 68:
                lbl68.setForeground(col);
                break;
                case 69:
                lbl69.setForeground(col);
                break;
                case 70:
                lbl70.setForeground(col);
                break;
                case 71:
                lbl71.setForeground(col);
                break;
                case 72:
                lbl72.setForeground(col);
                break;
                case 73:
                lbl73.setForeground(col);
                break;
                case 74:
                lbl74.setForeground(col);
                break;
                case 75:
                lbl75.setForeground(col);
                break;
                case 76:
                lbl76.setForeground(col);
                break;
                case 77:
                lbl77.setForeground(col);
                break;
                case 78:
                lbl78.setForeground(col);
                break;
                case 79:
                lbl79.setForeground(col);
                break;
                case 80:
                lbl80.setForeground(col);
                break;
                case 81:
                lbl81.setForeground(col);
                break;
                case 82:
                lbl82.setForeground(col);
                break;
                case 83:
                lbl83.setForeground(col);
                break;
                case 84:
                lbl84.setForeground(col);
                break;
                case 85:
                lbl85.setForeground(col);
                break;
                case 86:
                lbl86.setForeground(col);
                break;
                case 87:
                lbl87.setForeground(col);
                break;
                case 88:
                lbl88.setForeground(col);
                break;
                case 89:
                lbl89.setForeground(col);
                break;
                case 90:
                lbl90.setForeground(col);
                break;
                case 91:
                lbl91.setForeground(col);
                break;
                case 92:
                lbl92.setForeground(col);
                break;
                case 93:
                lbl93.setForeground(col);
                break;
                case 94:
                lbl94.setForeground(col);
                break;
                case 95:
                lbl95.setForeground(col);
                break;
                case 96:
                lbl96.setForeground(col);
                break;
                case 97:
                lbl97.setForeground(col);
                break;
                case 98:
                lbl98.setForeground(col);
                break;
                 case 99:
                lbl99.setForeground(col);
                break;
                 case 100:
                lbl100.setForeground(col);
                break;
                
        
                
    }
        
    }
    
            
            
            
            
            
            
            
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Snake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Snake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Snake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Snake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Snake().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl100;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl36;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lbl38;
    private javax.swing.JLabel lbl39;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbl45;
    private javax.swing.JLabel lbl46;
    private javax.swing.JLabel lbl47;
    private javax.swing.JLabel lbl48;
    private javax.swing.JLabel lbl49;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl50;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl52;
    private javax.swing.JLabel lbl53;
    private javax.swing.JLabel lbl54;
    private javax.swing.JLabel lbl55;
    private javax.swing.JLabel lbl56;
    private javax.swing.JLabel lbl57;
    private javax.swing.JLabel lbl58;
    private javax.swing.JLabel lbl59;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl60;
    private javax.swing.JLabel lbl61;
    private javax.swing.JLabel lbl62;
    private javax.swing.JLabel lbl63;
    private javax.swing.JLabel lbl64;
    private javax.swing.JLabel lbl65;
    private javax.swing.JLabel lbl66;
    private javax.swing.JLabel lbl67;
    private javax.swing.JLabel lbl68;
    private javax.swing.JLabel lbl69;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl70;
    private javax.swing.JLabel lbl71;
    private javax.swing.JLabel lbl72;
    private javax.swing.JLabel lbl73;
    private javax.swing.JLabel lbl74;
    private javax.swing.JLabel lbl75;
    private javax.swing.JLabel lbl76;
    private javax.swing.JLabel lbl77;
    private javax.swing.JLabel lbl78;
    private javax.swing.JLabel lbl79;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl80;
    private javax.swing.JLabel lbl81;
    private javax.swing.JLabel lbl82;
    private javax.swing.JLabel lbl83;
    private javax.swing.JLabel lbl84;
    private javax.swing.JLabel lbl85;
    private javax.swing.JLabel lbl86;
    private javax.swing.JLabel lbl87;
    private javax.swing.JLabel lbl88;
    private javax.swing.JLabel lbl89;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lbl90;
    private javax.swing.JLabel lbl91;
    private javax.swing.JLabel lbl92;
    private javax.swing.JLabel lbl93;
    private javax.swing.JLabel lbl94;
    private javax.swing.JLabel lbl95;
    private javax.swing.JLabel lbl96;
    private javax.swing.JLabel lbl97;
    private javax.swing.JLabel lbl98;
    private javax.swing.JLabel lbl99;
    private javax.swing.JLabel lblLadder1;
    private javax.swing.JLabel lblLadder2;
    private javax.swing.JLabel lblLadder3;
    private javax.swing.JLabel lblLadder4;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblSnake1;
    private javax.swing.JLabel lblSnake2;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JLabel lblValue;
    private javax.swing.JPanel pnl;
    // End of variables declaration//GEN-END:variables
}
